language: python

install:
  - pip install -r requirements.txt
script:
  - flake8
  - python -m unittest --verbose tests.test_default

jobs:
  include:
    - stage: "Unit tests"
      name: "Python 3.8 (Linux)"
      python: 3.8
    - name: "Python 3.5.0 (Linux)"
      python: 3.5.0
    - name: "Python 3.8 (Windows)"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.6
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 3.5.0 (Windows)"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.0
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
